---
title: Invoerknoppen gebruiken
hero_image: images/banner.png
description: Hoe de invoerknoppen op je micro:bit te gebruiken
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Inleiding

