title: Using input buttons
hero_image: images/banner.png
description: How to use input buttons on your micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Introduction

