title: Utiliser les boutons d'entrée
hero_image: images/banner.png
description: Comment utiliser les boutons d'entrée sur ton micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Introduction

